### ISSUE TITLE
Rigth side nav no se oculta 

### ISSUE THREAD

**Issue by Newville23** [FlugelTeam/storm-front#11]
Al interactuar con el menú del right side nave , este debe ocultarse .

**Comment by Lenninlasd** [comment]
de que parte de la app estamos hablando?

**Comment by Newville23** [comment]
Tranquilo que es el de la maqueta de el dashboard.

**Comment by Lenninlasd** [comment]
pero a mí sí se me oculta, incluso en http://fluguel.com/app/#/dash
